//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComaxMgt
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", ConfigurationName="ComaxMgt.ComaxMgt_Port")]
    public interface ComaxMgt_Port
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt:GetBill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ComaxMgt.GetBill_Result> GetBillAsync(ComaxMgt.GetBill request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt:GetBillPaymentDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ComaxMgt.GetBillPaymentDate_Result> GetBillPaymentDateAsync(ComaxMgt.GetBillPaymentDate request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt:GetLogo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ComaxMgt.GetLogo_Result> GetLogoAsync(ComaxMgt.GetLogo request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt:GetBackgroundPicture", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ComaxMgt.GetBackgroundPicture_Result> GetBackgroundPictureAsync(ComaxMgt.GetBackgroundPicture request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt:GetFont", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ComaxMgt.GetFont_Result> GetFontAsync(ComaxMgt.GetFont request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBill", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", IsWrapped=true)]
    public partial class GetBill
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", Order=0)]
        public string documentNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", Order=1)]
        public string bill;
        
        public GetBill()
        {
        }
        
        public GetBill(string documentNo, string bill)
        {
            this.documentNo = documentNo;
            this.bill = bill;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBill_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", IsWrapped=true)]
    public partial class GetBill_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", Order=0)]
        public string bill;
        
        public GetBill_Result()
        {
        }
        
        public GetBill_Result(string bill)
        {
            this.bill = bill;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBillPaymentDate", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", IsWrapped=true)]
    public partial class GetBillPaymentDate
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", Order=0)]
        public string lDocNo;
        
        public GetBillPaymentDate()
        {
        }
        
        public GetBillPaymentDate(string lDocNo)
        {
            this.lDocNo = lDocNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBillPaymentDate_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", IsWrapped=true)]
    public partial class GetBillPaymentDate_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime return_value;
        
        public GetBillPaymentDate_Result()
        {
        }
        
        public GetBillPaymentDate_Result(System.DateTime return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLogo", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", IsWrapped=true)]
    public partial class GetLogo
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", Order=0)]
        public string picture;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", Order=1)]
        public string extension;
        
        public GetLogo()
        {
        }
        
        public GetLogo(string picture, string extension)
        {
            this.picture = picture;
            this.extension = extension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLogo_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", IsWrapped=true)]
    public partial class GetLogo_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", Order=0)]
        public string picture;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", Order=1)]
        public string extension;
        
        public GetLogo_Result()
        {
        }
        
        public GetLogo_Result(string picture, string extension)
        {
            this.picture = picture;
            this.extension = extension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBackgroundPicture", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", IsWrapped=true)]
    public partial class GetBackgroundPicture
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", Order=0)]
        public string picture;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", Order=1)]
        public string extension;
        
        public GetBackgroundPicture()
        {
        }
        
        public GetBackgroundPicture(string picture, string extension)
        {
            this.picture = picture;
            this.extension = extension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBackgroundPicture_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", IsWrapped=true)]
    public partial class GetBackgroundPicture_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", Order=0)]
        public string picture;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", Order=1)]
        public string extension;
        
        public GetBackgroundPicture_Result()
        {
        }
        
        public GetBackgroundPicture_Result(string picture, string extension)
        {
            this.picture = picture;
            this.extension = extension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFont", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", IsWrapped=true)]
    public partial class GetFont
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", Order=1)]
        public string url;
        
        public GetFont()
        {
        }
        
        public GetFont(string name, string url)
        {
            this.name = name;
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFont_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", IsWrapped=true)]
    public partial class GetFont_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ComaxMgt", Order=1)]
        public string url;
        
        public GetFont_Result()
        {
        }
        
        public GetFont_Result(string name, string url)
        {
            this.name = name;
            this.url = url;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface ComaxMgt_PortChannel : ComaxMgt.ComaxMgt_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class ComaxMgt_PortClient : System.ServiceModel.ClientBase<ComaxMgt.ComaxMgt_Port>, ComaxMgt.ComaxMgt_Port
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ComaxMgt_PortClient() : 
                base(ComaxMgt_PortClient.GetDefaultBinding(), ComaxMgt_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ComaxMgt_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ComaxMgt_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(ComaxMgt_PortClient.GetBindingForEndpoint(endpointConfiguration), ComaxMgt_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ComaxMgt_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ComaxMgt_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ComaxMgt_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ComaxMgt_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ComaxMgt_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ComaxMgt.GetBill_Result> GetBillAsync(ComaxMgt.GetBill request)
        {
            return base.Channel.GetBillAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ComaxMgt.GetBillPaymentDate_Result> ComaxMgt.ComaxMgt_Port.GetBillPaymentDateAsync(ComaxMgt.GetBillPaymentDate request)
        {
            return base.Channel.GetBillPaymentDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ComaxMgt.GetBillPaymentDate_Result> GetBillPaymentDateAsync(string lDocNo)
        {
            ComaxMgt.GetBillPaymentDate inValue = new ComaxMgt.GetBillPaymentDate();
            inValue.lDocNo = lDocNo;
            return ((ComaxMgt.ComaxMgt_Port)(this)).GetBillPaymentDateAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ComaxMgt.GetLogo_Result> GetLogoAsync(ComaxMgt.GetLogo request)
        {
            return base.Channel.GetLogoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ComaxMgt.GetBackgroundPicture_Result> GetBackgroundPictureAsync(ComaxMgt.GetBackgroundPicture request)
        {
            return base.Channel.GetBackgroundPictureAsync(request);
        }
        
        public System.Threading.Tasks.Task<ComaxMgt.GetFont_Result> GetFontAsync(ComaxMgt.GetFont request)
        {
            return base.Channel.GetFontAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ComaxMgt_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ComaxMgt_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://20.87.10.102:30147/SBUBNZ/WS/My Voltage/Codeunit/ComaxMgt?tenant=1f998066-df" +
                        "97-4de7-875d-0179278815b1");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ComaxMgt_PortClient.GetBindingForEndpoint(EndpointConfiguration.ComaxMgt_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ComaxMgt_PortClient.GetEndpointAddress(EndpointConfiguration.ComaxMgt_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            ComaxMgt_Port,
        }
    }
}
