//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", ConfigurationName="ServiceReference2.WSManagement_Port")]
    public interface WSManagement_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSManagement:GetBillCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.GetBillCount_Result> GetBillCountAsync(ServiceReference2.GetBillCount request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSManagement:GetUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.GetUsers_Result> GetUsersAsync(ServiceReference2.GetUsers request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSManagement:CreateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.CreateUser_Result> CreateUserAsync(ServiceReference2.CreateUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSManagement:DeleteUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.DeleteUser_Result> DeleteUserAsync(ServiceReference2.DeleteUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSManagement:UserSetPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.UserSetPassword_Result> UserSetPasswordAsync(ServiceReference2.UserSetPassword request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSManagement:GetCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.GetCount_Result> GetCountAsync(ServiceReference2.GetCount request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSManagement:SetNotEnabled", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.SetNotEnabled_Result> SetNotEnabledAsync(ServiceReference2.SetNotEnabled request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WSManagement:PostReceiptJournal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.PostReceiptJournal_Result> PostReceiptJournalAsync(ServiceReference2.PostReceiptJournal request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBillCount", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", IsWrapped=true)]
    public partial class GetBillCount
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime endDate;
        
        public GetBillCount()
        {
        }
        
        public GetBillCount(System.DateTime startDate, System.DateTime endDate)
        {
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBillCount_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", IsWrapped=true)]
    public partial class GetBillCount_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=0)]
        public int return_value;
        
        public GetBillCount_Result()
        {
        }
        
        public GetBillCount_Result(int return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsers", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", IsWrapped=true)]
    public partial class GetUsers
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=0)]
        public string users;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=1)]
        public int userCount;
        
        public GetUsers()
        {
        }
        
        public GetUsers(string users, int userCount)
        {
            this.users = users;
            this.userCount = userCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsers_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", IsWrapped=true)]
    public partial class GetUsers_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=0)]
        public string users;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=1)]
        public int userCount;
        
        public GetUsers_Result()
        {
        }
        
        public GetUsers_Result(string users, int userCount)
        {
            this.users = users;
            this.userCount = userCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUser", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", IsWrapped=true)]
    public partial class CreateUser
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=1)]
        public string password;
        
        public CreateUser()
        {
        }
        
        public CreateUser(string userName, string password)
        {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateUser_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", IsWrapped=true)]
    public partial class CreateUser_Result
    {
        
        public CreateUser_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteUser", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", IsWrapped=true)]
    public partial class DeleteUser
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=0)]
        public string userName;
        
        public DeleteUser()
        {
        }
        
        public DeleteUser(string userName)
        {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteUser_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", IsWrapped=true)]
    public partial class DeleteUser_Result
    {
        
        public DeleteUser_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserSetPassword", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", IsWrapped=true)]
    public partial class UserSetPassword
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=1)]
        public string password;
        
        public UserSetPassword()
        {
        }
        
        public UserSetPassword(string userName, string password)
        {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserSetPassword_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", IsWrapped=true)]
    public partial class UserSetPassword_Result
    {
        
        public UserSetPassword_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCount", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", IsWrapped=true)]
    public partial class GetCount
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=0)]
        public int tableNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=1)]
        public string tableFilter;
        
        public GetCount()
        {
        }
        
        public GetCount(int tableNo, string tableFilter)
        {
            this.tableNo = tableNo;
            this.tableFilter = tableFilter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCount_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", IsWrapped=true)]
    public partial class GetCount_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=0)]
        public int return_value;
        
        public GetCount_Result()
        {
        }
        
        public GetCount_Result(int return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetNotEnabled", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", IsWrapped=true)]
    public partial class SetNotEnabled
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=0)]
        public int tableNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=1)]
        public string tableFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=2)]
        public int enableFieldNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=3)]
        public string enabledFieldValue;
        
        public SetNotEnabled()
        {
        }
        
        public SetNotEnabled(int tableNo, string tableFilter, int enableFieldNo, string enabledFieldValue)
        {
            this.tableNo = tableNo;
            this.tableFilter = tableFilter;
            this.enableFieldNo = enableFieldNo;
            this.enabledFieldValue = enabledFieldValue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetNotEnabled_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", IsWrapped=true)]
    public partial class SetNotEnabled_Result
    {
        
        public SetNotEnabled_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostReceiptJournal", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", IsWrapped=true)]
    public partial class PostReceiptJournal
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=0)]
        public string jnlTemplateName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=1)]
        public string jnlBatchName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", Order=2)]
        public int lineNo;
        
        public PostReceiptJournal()
        {
        }
        
        public PostReceiptJournal(string jnlTemplateName, string jnlBatchName, int lineNo)
        {
            this.jnlTemplateName = jnlTemplateName;
            this.jnlBatchName = jnlBatchName;
            this.lineNo = lineNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostReceiptJournal_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WSManagement", IsWrapped=true)]
    public partial class PostReceiptJournal_Result
    {
        
        public PostReceiptJournal_Result()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface WSManagement_PortChannel : ServiceReference2.WSManagement_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class WSManagement_PortClient : System.ServiceModel.ClientBase<ServiceReference2.WSManagement_Port>, ServiceReference2.WSManagement_Port
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSManagement_PortClient() : 
                base(WSManagement_PortClient.GetDefaultBinding(), WSManagement_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSManagement_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSManagement_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(WSManagement_PortClient.GetBindingForEndpoint(endpointConfiguration), WSManagement_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSManagement_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSManagement_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSManagement_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSManagement_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSManagement_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.GetBillCount_Result> ServiceReference2.WSManagement_Port.GetBillCountAsync(ServiceReference2.GetBillCount request)
        {
            return base.Channel.GetBillCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.GetBillCount_Result> GetBillCountAsync(System.DateTime startDate, System.DateTime endDate)
        {
            ServiceReference2.GetBillCount inValue = new ServiceReference2.GetBillCount();
            inValue.startDate = startDate;
            inValue.endDate = endDate;
            return ((ServiceReference2.WSManagement_Port)(this)).GetBillCountAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.GetUsers_Result> GetUsersAsync(ServiceReference2.GetUsers request)
        {
            return base.Channel.GetUsersAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.CreateUser_Result> ServiceReference2.WSManagement_Port.CreateUserAsync(ServiceReference2.CreateUser request)
        {
            return base.Channel.CreateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.CreateUser_Result> CreateUserAsync(string userName, string password)
        {
            ServiceReference2.CreateUser inValue = new ServiceReference2.CreateUser();
            inValue.userName = userName;
            inValue.password = password;
            return ((ServiceReference2.WSManagement_Port)(this)).CreateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.DeleteUser_Result> ServiceReference2.WSManagement_Port.DeleteUserAsync(ServiceReference2.DeleteUser request)
        {
            return base.Channel.DeleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.DeleteUser_Result> DeleteUserAsync(string userName)
        {
            ServiceReference2.DeleteUser inValue = new ServiceReference2.DeleteUser();
            inValue.userName = userName;
            return ((ServiceReference2.WSManagement_Port)(this)).DeleteUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.UserSetPassword_Result> ServiceReference2.WSManagement_Port.UserSetPasswordAsync(ServiceReference2.UserSetPassword request)
        {
            return base.Channel.UserSetPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.UserSetPassword_Result> UserSetPasswordAsync(string userName, string password)
        {
            ServiceReference2.UserSetPassword inValue = new ServiceReference2.UserSetPassword();
            inValue.userName = userName;
            inValue.password = password;
            return ((ServiceReference2.WSManagement_Port)(this)).UserSetPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.GetCount_Result> ServiceReference2.WSManagement_Port.GetCountAsync(ServiceReference2.GetCount request)
        {
            return base.Channel.GetCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.GetCount_Result> GetCountAsync(int tableNo, string tableFilter)
        {
            ServiceReference2.GetCount inValue = new ServiceReference2.GetCount();
            inValue.tableNo = tableNo;
            inValue.tableFilter = tableFilter;
            return ((ServiceReference2.WSManagement_Port)(this)).GetCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.SetNotEnabled_Result> ServiceReference2.WSManagement_Port.SetNotEnabledAsync(ServiceReference2.SetNotEnabled request)
        {
            return base.Channel.SetNotEnabledAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.SetNotEnabled_Result> SetNotEnabledAsync(int tableNo, string tableFilter, int enableFieldNo, string enabledFieldValue)
        {
            ServiceReference2.SetNotEnabled inValue = new ServiceReference2.SetNotEnabled();
            inValue.tableNo = tableNo;
            inValue.tableFilter = tableFilter;
            inValue.enableFieldNo = enableFieldNo;
            inValue.enabledFieldValue = enabledFieldValue;
            return ((ServiceReference2.WSManagement_Port)(this)).SetNotEnabledAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.PostReceiptJournal_Result> ServiceReference2.WSManagement_Port.PostReceiptJournalAsync(ServiceReference2.PostReceiptJournal request)
        {
            return base.Channel.PostReceiptJournalAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.PostReceiptJournal_Result> PostReceiptJournalAsync(string jnlTemplateName, string jnlBatchName, int lineNo)
        {
            ServiceReference2.PostReceiptJournal inValue = new ServiceReference2.PostReceiptJournal();
            inValue.jnlTemplateName = jnlTemplateName;
            inValue.jnlBatchName = jnlBatchName;
            inValue.lineNo = lineNo;
            return ((ServiceReference2.WSManagement_Port)(this)).PostReceiptJournalAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSManagement_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSManagement_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://20.87.10.102:30147/SBUBNZ/WS/TEST MY VOLTAGE/Codeunit/WSManagement?tenant=1f" +
                        "998066-df97-4de7-875d-0179278815b1");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSManagement_PortClient.GetBindingForEndpoint(EndpointConfiguration.WSManagement_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSManagement_PortClient.GetEndpointAddress(EndpointConfiguration.WSManagement_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            WSManagement_Port,
        }
    }
}
