//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", ConfigurationName="ServiceReference1.CashReceiptJournal_Port")]
    public interface CashReceiptJournal_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/cashreceiptjournal:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.ReadByRecId_Result> ReadByRecIdAsync(ServiceReference1.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/cashreceiptjournal:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.ReadMultiple_Result> ReadMultipleAsync(ServiceReference1.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/cashreceiptjournal:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.IsUpdated_Result> IsUpdatedAsync(ServiceReference1.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/cashreceiptjournal:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(ServiceReference1.GetRecIdFromKey request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/cashreceiptjournal:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.Create_Result> CreateAsync(ServiceReference1.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/cashreceiptjournal:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.CreateMultiple_Result> CreateMultipleAsync(ServiceReference1.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/cashreceiptjournal:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.Update_Result> UpdateAsync(ServiceReference1.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/cashreceiptjournal:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.UpdateMultiple_Result> UpdateMultipleAsync(ServiceReference1.UpdateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/cashreceiptjournal:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.Delete_Result> DeleteAsync(ServiceReference1.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal")]
    public partial class CashReceiptJournal
    {
        
        private string keyField;
        
        private System.DateTime posting_DateField;
        
        private bool posting_DateFieldSpecified;
        
        private System.DateTime document_DateField;
        
        private bool document_DateFieldSpecified;
        
        private Document_Type document_TypeField;
        
        private bool document_TypeFieldSpecified;
        
        private string document_NoField;
        
        private int incoming_Document_Entry_NoField;
        
        private bool incoming_Document_Entry_NoFieldSpecified;
        
        private string external_Document_NoField;
        
        private Account_Type account_TypeField;
        
        private bool account_TypeFieldSpecified;
        
        private string account_NoField;
        
        private string descriptionField;
        
        private string wHT_Business_Posting_GroupField;
        
        private string wHT_Product_Posting_GroupField;
        
        private string salespers_Purch_CodeField;
        
        private string campaign_NoField;
        
        private string currency_CodeField;
        
        private Gen_Posting_Type gen_Posting_TypeField;
        
        private bool gen_Posting_TypeFieldSpecified;
        
        private string gen_Bus_Posting_GroupField;
        
        private string gen_Prod_Posting_GroupField;
        
        private string vAT_Bus_Posting_GroupField;
        
        private string vAT_Prod_Posting_GroupField;
        
        private bool wHT_PaymentField;
        
        private bool wHT_PaymentFieldSpecified;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private decimal debit_AmountField;
        
        private bool debit_AmountFieldSpecified;
        
        private decimal credit_AmountField;
        
        private bool credit_AmountFieldSpecified;
        
        private decimal vAT_AmountField;
        
        private bool vAT_AmountFieldSpecified;
        
        private decimal vAT_DifferenceField;
        
        private bool vAT_DifferenceFieldSpecified;
        
        private decimal bal_VAT_AmountField;
        
        private bool bal_VAT_AmountFieldSpecified;
        
        private decimal bal_VAT_DifferenceField;
        
        private bool bal_VAT_DifferenceFieldSpecified;
        
        private Bal_Account_Type bal_Account_TypeField;
        
        private bool bal_Account_TypeFieldSpecified;
        
        private string bal_Account_NoField;
        
        private Bal_Gen_Posting_Type bal_Gen_Posting_TypeField;
        
        private bool bal_Gen_Posting_TypeFieldSpecified;
        
        private string bal_Gen_Bus_Posting_GroupField;
        
        private string bal_Gen_Prod_Posting_GroupField;
        
        private string bal_VAT_Bus_Posting_GroupField;
        
        private string customer_Vendor_BankField;
        
        private string bank_Branch_NoField;
        
        private string bank_Account_NoField;
        
        private string bal_VAT_Prod_Posting_GroupField;
        
        private string shortcut_Dimension_1_CodeField;
        
        private string shortcut_Dimension_2_CodeField;
        
        private string shortcutDimCode3Field;
        
        private string shortcutDimCode4Field;
        
        private string shortcutDimCode5Field;
        
        private string shortcutDimCode6Field;
        
        private string shortcutDimCode7Field;
        
        private string shortcutDimCode8Field;
        
        private bool applied_Yes_NoField;
        
        private bool applied_Yes_NoFieldSpecified;
        
        private Applies_to_Doc_Type applies_to_Doc_TypeField;
        
        private bool applies_to_Doc_TypeFieldSpecified;
        
        private string applies_to_Doc_NoField;
        
        private string applies_to_IDField;
        
        private string reason_CodeField;
        
        private string commentField;
        
        private string direct_Debit_Mandate_IDField;
        
        private bool orderImportedField;
        
        private bool orderImportedFieldSpecified;
        
        private bool orderConfirmedField;
        
        private bool orderConfirmedFieldSpecified;
        
        private string information_from_BankField;
        
        private string invoice_NoField;
        
        private string invoice_No_2Field;
        
        private string accNameField;
        
        private string balAccNameField;
        
        private decimal balanceField;
        
        private bool balanceFieldSpecified;
        
        private decimal totalBalanceField;
        
        private bool totalBalanceFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {

                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime Posting_Date
        {
            get
            {
                return this.posting_DateField;
            }
            set
            {
                this.posting_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Posting_DateSpecified
        {
            get
            {
                return this.posting_DateFieldSpecified;
            }
            set
            {
                this.posting_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime Document_Date
        {
            get
            {
                return this.document_DateField;
            }
            set
            {
                this.document_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Document_DateSpecified
        {
            get
            {
                return this.document_DateFieldSpecified;
            }
            set
            {
                this.document_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Document_Type Document_Type
        {
            get
            {
                return this.document_TypeField;
            }
            set
            {
                this.document_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Document_TypeSpecified
        {
            get
            {
                return this.document_TypeFieldSpecified;
            }
            set
            {
                this.document_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Document_No
        {
            get
            {
                return this.document_NoField;
            }
            set
            {
                this.document_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Incoming_Document_Entry_No
        {
            get
            {
                return this.incoming_Document_Entry_NoField;
            }
            set
            {
                this.incoming_Document_Entry_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Incoming_Document_Entry_NoSpecified
        {
            get
            {
                return this.incoming_Document_Entry_NoFieldSpecified;
            }
            set
            {
                this.incoming_Document_Entry_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string External_Document_No
        {
            get
            {
                return this.external_Document_NoField;
            }
            set
            {
                this.external_Document_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Account_Type Account_Type
        {
            get
            {
                return this.account_TypeField;
            }
            set
            {
                this.account_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Account_TypeSpecified
        {
            get
            {
                return this.account_TypeFieldSpecified;
            }
            set
            {
                this.account_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Account_No
        {
            get
            {
                return this.account_NoField;
            }
            set
            {
                this.account_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string WHT_Business_Posting_Group
        {
            get
            {
                return this.wHT_Business_Posting_GroupField;
            }
            set
            {
                this.wHT_Business_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string WHT_Product_Posting_Group
        {
            get
            {
                return this.wHT_Product_Posting_GroupField;
            }
            set
            {
                this.wHT_Product_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Salespers_Purch_Code
        {
            get
            {
                return this.salespers_Purch_CodeField;
            }
            set
            {
                this.salespers_Purch_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Campaign_No
        {
            get
            {
                return this.campaign_NoField;
            }
            set
            {
                this.campaign_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Currency_Code
        {
            get
            {
                return this.currency_CodeField;
            }
            set
            {
                this.currency_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public Gen_Posting_Type Gen_Posting_Type
        {
            get
            {
                return this.gen_Posting_TypeField;
            }
            set
            {
                this.gen_Posting_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Gen_Posting_TypeSpecified
        {
            get
            {
                return this.gen_Posting_TypeFieldSpecified;
            }
            set
            {
                this.gen_Posting_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Gen_Bus_Posting_Group
        {
            get
            {
                return this.gen_Bus_Posting_GroupField;
            }
            set
            {
                this.gen_Bus_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Gen_Prod_Posting_Group
        {
            get
            {
                return this.gen_Prod_Posting_GroupField;
            }
            set
            {
                this.gen_Prod_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string VAT_Bus_Posting_Group
        {
            get
            {
                return this.vAT_Bus_Posting_GroupField;
            }
            set
            {
                this.vAT_Bus_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string VAT_Prod_Posting_Group
        {
            get
            {
                return this.vAT_Prod_Posting_GroupField;
            }
            set
            {
                this.vAT_Prod_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public bool WHT_Payment
        {
            get
            {
                return this.wHT_PaymentField;
            }
            set
            {
                this.wHT_PaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WHT_PaymentSpecified
        {
            get
            {
                return this.wHT_PaymentFieldSpecified;
            }
            set
            {
                this.wHT_PaymentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified
        {
            get
            {
                return this.amountFieldSpecified;
            }
            set
            {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public decimal Debit_Amount
        {
            get
            {
                return this.debit_AmountField;
            }
            set
            {
                this.debit_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Debit_AmountSpecified
        {
            get
            {
                return this.debit_AmountFieldSpecified;
            }
            set
            {
                this.debit_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public decimal Credit_Amount
        {
            get
            {
                return this.credit_AmountField;
            }
            set
            {
                this.credit_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Credit_AmountSpecified
        {
            get
            {
                return this.credit_AmountFieldSpecified;
            }
            set
            {
                this.credit_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public decimal VAT_Amount
        {
            get
            {
                return this.vAT_AmountField;
            }
            set
            {
                this.vAT_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VAT_AmountSpecified
        {
            get
            {
                return this.vAT_AmountFieldSpecified;
            }
            set
            {
                this.vAT_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public decimal VAT_Difference
        {
            get
            {
                return this.vAT_DifferenceField;
            }
            set
            {
                this.vAT_DifferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VAT_DifferenceSpecified
        {
            get
            {
                return this.vAT_DifferenceFieldSpecified;
            }
            set
            {
                this.vAT_DifferenceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public decimal Bal_VAT_Amount
        {
            get
            {
                return this.bal_VAT_AmountField;
            }
            set
            {
                this.bal_VAT_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Bal_VAT_AmountSpecified
        {
            get
            {
                return this.bal_VAT_AmountFieldSpecified;
            }
            set
            {
                this.bal_VAT_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public decimal Bal_VAT_Difference
        {
            get
            {
                return this.bal_VAT_DifferenceField;
            }
            set
            {
                this.bal_VAT_DifferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Bal_VAT_DifferenceSpecified
        {
            get
            {
                return this.bal_VAT_DifferenceFieldSpecified;
            }
            set
            {
                this.bal_VAT_DifferenceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public Bal_Account_Type Bal_Account_Type
        {
            get
            {
                return this.bal_Account_TypeField;
            }
            set
            {
                this.bal_Account_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Bal_Account_TypeSpecified
        {
            get
            {
                return this.bal_Account_TypeFieldSpecified;
            }
            set
            {
                this.bal_Account_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string Bal_Account_No
        {
            get
            {
                return this.bal_Account_NoField;
            }
            set
            {
                this.bal_Account_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public Bal_Gen_Posting_Type Bal_Gen_Posting_Type
        {
            get
            {
                return this.bal_Gen_Posting_TypeField;
            }
            set
            {
                this.bal_Gen_Posting_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Bal_Gen_Posting_TypeSpecified
        {
            get
            {
                return this.bal_Gen_Posting_TypeFieldSpecified;
            }
            set
            {
                this.bal_Gen_Posting_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string Bal_Gen_Bus_Posting_Group
        {
            get
            {
                return this.bal_Gen_Bus_Posting_GroupField;
            }
            set
            {
                this.bal_Gen_Bus_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string Bal_Gen_Prod_Posting_Group
        {
            get
            {
                return this.bal_Gen_Prod_Posting_GroupField;
            }
            set
            {
                this.bal_Gen_Prod_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string Bal_VAT_Bus_Posting_Group
        {
            get
            {
                return this.bal_VAT_Bus_Posting_GroupField;
            }
            set
            {
                this.bal_VAT_Bus_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string Customer_Vendor_Bank
        {
            get
            {
                return this.customer_Vendor_BankField;
            }
            set
            {
                this.customer_Vendor_BankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string Bank_Branch_No
        {
            get
            {
                return this.bank_Branch_NoField;
            }
            set
            {
                this.bank_Branch_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string Bank_Account_No
        {
            get
            {
                return this.bank_Account_NoField;
            }
            set
            {
                this.bank_Account_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string Bal_VAT_Prod_Posting_Group
        {
            get
            {
                return this.bal_VAT_Prod_Posting_GroupField;
            }
            set
            {
                this.bal_VAT_Prod_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string Shortcut_Dimension_1_Code
        {
            get
            {
                return this.shortcut_Dimension_1_CodeField;
            }
            set
            {
                this.shortcut_Dimension_1_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string Shortcut_Dimension_2_Code
        {
            get
            {
                return this.shortcut_Dimension_2_CodeField;
            }
            set
            {
                this.shortcut_Dimension_2_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[3]", Order=40)]
        public string ShortcutDimCode3
        {
            get
            {
                return this.shortcutDimCode3Field;
            }
            set
            {
                this.shortcutDimCode3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[4]", Order=41)]
        public string ShortcutDimCode4
        {
            get
            {
                return this.shortcutDimCode4Field;
            }
            set
            {
                this.shortcutDimCode4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[5]", Order=42)]
        public string ShortcutDimCode5
        {
            get
            {
                return this.shortcutDimCode5Field;
            }
            set
            {
                this.shortcutDimCode5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[6]", Order=43)]
        public string ShortcutDimCode6
        {
            get
            {
                return this.shortcutDimCode6Field;
            }
            set
            {
                this.shortcutDimCode6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[7]", Order=44)]
        public string ShortcutDimCode7
        {
            get
            {
                return this.shortcutDimCode7Field;
            }
            set
            {
                this.shortcutDimCode7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[8]", Order=45)]
        public string ShortcutDimCode8
        {
            get
            {
                return this.shortcutDimCode8Field;
            }
            set
            {
                this.shortcutDimCode8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public bool Applied_Yes_No
        {
            get
            {
                return this.applied_Yes_NoField;
            }
            set
            {
                this.applied_Yes_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Applied_Yes_NoSpecified
        {
            get
            {
                return this.applied_Yes_NoFieldSpecified;
            }
            set
            {
                this.applied_Yes_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public Applies_to_Doc_Type Applies_to_Doc_Type
        {
            get
            {
                return this.applies_to_Doc_TypeField;
            }
            set
            {
                this.applies_to_Doc_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Applies_to_Doc_TypeSpecified
        {
            get
            {
                return this.applies_to_Doc_TypeFieldSpecified;
            }
            set
            {
                this.applies_to_Doc_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string Applies_to_Doc_No
        {
            get
            {
                return this.applies_to_Doc_NoField;
            }
            set
            {
                this.applies_to_Doc_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string Applies_to_ID
        {
            get
            {
                return this.applies_to_IDField;
            }
            set
            {
                this.applies_to_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string Reason_Code
        {
            get
            {
                return this.reason_CodeField;
            }
            set
            {
                this.reason_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string Direct_Debit_Mandate_ID
        {
            get
            {
                return this.direct_Debit_Mandate_IDField;
            }
            set
            {
                this.direct_Debit_Mandate_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public bool OrderImported
        {
            get
            {
                return this.orderImportedField;
            }
            set
            {
                this.orderImportedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderImportedSpecified
        {
            get
            {
                return this.orderImportedFieldSpecified;
            }
            set
            {
                this.orderImportedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public bool OrderConfirmed
        {
            get
            {
                return this.orderConfirmedField;
            }
            set
            {
                this.orderConfirmedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderConfirmedSpecified
        {
            get
            {
                return this.orderConfirmedFieldSpecified;
            }
            set
            {
                this.orderConfirmedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string Information_from_Bank
        {
            get
            {
                return this.information_from_BankField;
            }
            set
            {
                this.information_from_BankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public string Invoice_No
        {
            get
            {
                return this.invoice_NoField;
            }
            set
            {
                this.invoice_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public string Invoice_No_2
        {
            get
            {
                return this.invoice_No_2Field;
            }
            set
            {
                this.invoice_No_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public string AccName
        {
            get
            {
                return this.accNameField;
            }
            set
            {
                this.accNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public string BalAccName
        {
            get
            {
                return this.balAccNameField;
            }
            set
            {
                this.balAccNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public decimal Balance
        {
            get
            {
                return this.balanceField;
            }
            set
            {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BalanceSpecified
        {
            get
            {
                return this.balanceFieldSpecified;
            }
            set
            {
                this.balanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public decimal TotalBalance
        {
            get
            {
                return this.totalBalanceField;
            }
            set
            {
                this.totalBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalBalanceSpecified
        {
            get
            {
                return this.totalBalanceFieldSpecified;
            }
            set
            {
                this.totalBalanceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal")]
    public enum Document_Type
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Payment,
        
        /// <remarks/>
        Invoice,
        
        /// <remarks/>
        Credit_Memo,
        
        /// <remarks/>
        Finance_Charge_Memo,
        
        /// <remarks/>
        Reminder,
        
        /// <remarks/>
        Refund,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal")]
    public enum Account_Type
    {
        
        /// <remarks/>
        G_L_Account,
        
        /// <remarks/>
        Customer,
        
        /// <remarks/>
        Vendor,
        
        /// <remarks/>
        Bank_Account,
        
        /// <remarks/>
        Fixed_Asset,
        
        /// <remarks/>
        IC_Partner,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal")]
    public enum Gen_Posting_Type
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Purchase,
        
        /// <remarks/>
        Sale,
        
        /// <remarks/>
        Settlement,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal")]
    public enum Bal_Account_Type
    {
        
        /// <remarks/>
        G_L_Account,
        
        /// <remarks/>
        Customer,
        
        /// <remarks/>
        Vendor,
        
        /// <remarks/>
        Bank_Account,
        
        /// <remarks/>
        Fixed_Asset,
        
        /// <remarks/>
        IC_Partner,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal")]
    public enum Bal_Gen_Posting_Type
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Purchase,
        
        /// <remarks/>
        Sale,
        
        /// <remarks/>
        Settlement,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal")]
    public enum Applies_to_Doc_Type
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Payment,
        
        /// <remarks/>
        Invoice,
        
        /// <remarks/>
        Credit_Memo,
        
        /// <remarks/>
        Finance_Charge_Memo,
        
        /// <remarks/>
        Reminder,
        
        /// <remarks/>
        Refund,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal")]
    public partial class CashReceiptJournal_Filter
    {
        
        private CashReceiptJournal_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CashReceiptJournal_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal")]
    public enum CashReceiptJournal_Fields
    {
        
        /// <remarks/>
        Posting_Date,
        
        /// <remarks/>
        Document_Date,
        
        /// <remarks/>
        Document_Type,
        
        /// <remarks/>
        Document_No,
        
        /// <remarks/>
        Incoming_Document_Entry_No,
        
        /// <remarks/>
        External_Document_No,
        
        /// <remarks/>
        Account_Type,
        
        /// <remarks/>
        Account_No,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        WHT_Business_Posting_Group,
        
        /// <remarks/>
        WHT_Product_Posting_Group,
        
        /// <remarks/>
        Salespers_Purch_Code,
        
        /// <remarks/>
        Campaign_No,
        
        /// <remarks/>
        Currency_Code,
        
        /// <remarks/>
        Gen_Posting_Type,
        
        /// <remarks/>
        Gen_Bus_Posting_Group,
        
        /// <remarks/>
        Gen_Prod_Posting_Group,
        
        /// <remarks/>
        VAT_Bus_Posting_Group,
        
        /// <remarks/>
        VAT_Prod_Posting_Group,
        
        /// <remarks/>
        WHT_Payment,
        
        /// <remarks/>
        Amount,
        
        /// <remarks/>
        Debit_Amount,
        
        /// <remarks/>
        Credit_Amount,
        
        /// <remarks/>
        VAT_Amount,
        
        /// <remarks/>
        VAT_Difference,
        
        /// <remarks/>
        Bal_VAT_Amount,
        
        /// <remarks/>
        Bal_VAT_Difference,
        
        /// <remarks/>
        Bal_Account_Type,
        
        /// <remarks/>
        Bal_Account_No,
        
        /// <remarks/>
        Bal_Gen_Posting_Type,
        
        /// <remarks/>
        Bal_Gen_Bus_Posting_Group,
        
        /// <remarks/>
        Bal_Gen_Prod_Posting_Group,
        
        /// <remarks/>
        Bal_VAT_Bus_Posting_Group,
        
        /// <remarks/>
        Customer_Vendor_Bank,
        
        /// <remarks/>
        Bank_Branch_No,
        
        /// <remarks/>
        Bank_Account_No,
        
        /// <remarks/>
        Bal_VAT_Prod_Posting_Group,
        
        /// <remarks/>
        Shortcut_Dimension_1_Code,
        
        /// <remarks/>
        Shortcut_Dimension_2_Code,
        
        /// <remarks/>
        ShortcutDimCode_x005B_3_x005D_,
        
        /// <remarks/>
        ShortcutDimCode_x005B_4_x005D_,
        
        /// <remarks/>
        ShortcutDimCode_x005B_5_x005D_,
        
        /// <remarks/>
        ShortcutDimCode_x005B_6_x005D_,
        
        /// <remarks/>
        ShortcutDimCode_x005B_7_x005D_,
        
        /// <remarks/>
        ShortcutDimCode_x005B_8_x005D_,
        
        /// <remarks/>
        Applied_Yes_No,
        
        /// <remarks/>
        Applies_to_Doc_Type,
        
        /// <remarks/>
        Applies_to_Doc_No,
        
        /// <remarks/>
        Applies_to_ID,
        
        /// <remarks/>
        Reason_Code,
        
        /// <remarks/>
        Comment,
        
        /// <remarks/>
        Direct_Debit_Mandate_ID,
        
        /// <remarks/>
        OrderImported,
        
        /// <remarks/>
        OrderConfirmed,
        
        /// <remarks/>
        Information_from_Bank,
        
        /// <remarks/>
        Invoice_No,
        
        /// <remarks/>
        Invoice_No_2,
        
        /// <remarks/>
        AccName,
        
        /// <remarks/>
        BalAccName,
        
        /// <remarks/>
        Balance,
        
        /// <remarks/>
        TotalBalance,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=0)]
        public string CurrentJnlBatchName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=1)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string CurrentJnlBatchName, string recId)
        {
            this.CurrentJnlBatchName = CurrentJnlBatchName;
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=0)]
        public ServiceReference1.CashReceiptJournal CashReceiptJournal;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(ServiceReference1.CashReceiptJournal CashReceiptJournal)
        {
            this.CashReceiptJournal = CashReceiptJournal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=0)]
        public string CurrentJnlBatchName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public ServiceReference1.CashReceiptJournal_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=2)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=3)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(string CurrentJnlBatchName, ServiceReference1.CashReceiptJournal_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.CurrentJnlBatchName = CurrentJnlBatchName;
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceReference1.CashReceiptJournal[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(ServiceReference1.CashReceiptJournal[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=0)]
        public string CurrentJnlBatchName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=1)]
        public ServiceReference1.CashReceiptJournal CashReceiptJournal;
        
        public Create()
        {
        }
        
        public Create(string CurrentJnlBatchName, ServiceReference1.CashReceiptJournal CashReceiptJournal)
        {
            this.CurrentJnlBatchName = CurrentJnlBatchName;
            this.CashReceiptJournal = CashReceiptJournal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=0)]
        public ServiceReference1.CashReceiptJournal CashReceiptJournal;
        
        public Create_Result()
        {
        }
        
        public Create_Result(ServiceReference1.CashReceiptJournal CashReceiptJournal)
        {
            this.CashReceiptJournal = CashReceiptJournal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=0)]
        public string CurrentJnlBatchName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceReference1.CashReceiptJournal[] CashReceiptJournal_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(string CurrentJnlBatchName, ServiceReference1.CashReceiptJournal[] CashReceiptJournal_List)
        {
            this.CurrentJnlBatchName = CurrentJnlBatchName;
            this.CashReceiptJournal_List = CashReceiptJournal_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceReference1.CashReceiptJournal[] CashReceiptJournal_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(ServiceReference1.CashReceiptJournal[] CashReceiptJournal_List)
        {
            this.CashReceiptJournal_List = CashReceiptJournal_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=0)]
        public string CurrentJnlBatchName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=1)]
        public ServiceReference1.CashReceiptJournal CashReceiptJournal;
        
        public Update()
        {
        }
        
        public Update(string CurrentJnlBatchName, ServiceReference1.CashReceiptJournal CashReceiptJournal)
        {
            this.CurrentJnlBatchName = CurrentJnlBatchName;
            this.CashReceiptJournal = CashReceiptJournal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=0)]
        public ServiceReference1.CashReceiptJournal CashReceiptJournal;
        
        public Update_Result()
        {
        }
        
        public Update_Result(ServiceReference1.CashReceiptJournal CashReceiptJournal)
        {
            this.CashReceiptJournal = CashReceiptJournal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=0)]
        public string CurrentJnlBatchName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceReference1.CashReceiptJournal[] CashReceiptJournal_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(string CurrentJnlBatchName, ServiceReference1.CashReceiptJournal[] CashReceiptJournal_List)
        {
            this.CurrentJnlBatchName = CurrentJnlBatchName;
            this.CashReceiptJournal_List = CashReceiptJournal_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceReference1.CashReceiptJournal[] CashReceiptJournal_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(ServiceReference1.CashReceiptJournal[] CashReceiptJournal_List)
        {
            this.CashReceiptJournal_List = CashReceiptJournal_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", IsWrapped=true)]
    public partial class Delete
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=0)]
        public string CurrentJnlBatchName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=1)]
        public string Key;
        
        public Delete()
        {
        }
        
        public Delete(string CurrentJnlBatchName, string Key)
        {
            this.CurrentJnlBatchName = CurrentJnlBatchName;
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", IsWrapped=true)]
    public partial class Delete_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/cashreceiptjournal", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result()
        {
        }
        
        public Delete_Result(bool Delete_Result1)
        {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface CashReceiptJournal_PortChannel : ServiceReference1.CashReceiptJournal_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class CashReceiptJournal_PortClient : System.ServiceModel.ClientBase<ServiceReference1.CashReceiptJournal_Port>, ServiceReference1.CashReceiptJournal_Port
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CashReceiptJournal_PortClient() : 
                base(CashReceiptJournal_PortClient.GetDefaultBinding(), CashReceiptJournal_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CashReceiptJournal_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CashReceiptJournal_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(CashReceiptJournal_PortClient.GetBindingForEndpoint(endpointConfiguration), CashReceiptJournal_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CashReceiptJournal_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CashReceiptJournal_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CashReceiptJournal_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CashReceiptJournal_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CashReceiptJournal_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ReadByRecId_Result> ServiceReference1.CashReceiptJournal_Port.ReadByRecIdAsync(ServiceReference1.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ReadByRecId_Result> ReadByRecIdAsync(string CurrentJnlBatchName, string recId)
        {
            ServiceReference1.ReadByRecId inValue = new ServiceReference1.ReadByRecId();
            inValue.CurrentJnlBatchName = CurrentJnlBatchName;
            inValue.recId = recId;
            return ((ServiceReference1.CashReceiptJournal_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ReadMultiple_Result> ServiceReference1.CashReceiptJournal_Port.ReadMultipleAsync(ServiceReference1.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ReadMultiple_Result> ReadMultipleAsync(string CurrentJnlBatchName, ServiceReference1.CashReceiptJournal_Filter[] filter, string bookmarkKey, int setSize)
        {
            ServiceReference1.ReadMultiple inValue = new ServiceReference1.ReadMultiple();
            inValue.CurrentJnlBatchName = CurrentJnlBatchName;
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((ServiceReference1.CashReceiptJournal_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.IsUpdated_Result> ServiceReference1.CashReceiptJournal_Port.IsUpdatedAsync(ServiceReference1.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            ServiceReference1.IsUpdated inValue = new ServiceReference1.IsUpdated();
            inValue.Key = Key;
            return ((ServiceReference1.CashReceiptJournal_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetRecIdFromKey_Result> ServiceReference1.CashReceiptJournal_Port.GetRecIdFromKeyAsync(ServiceReference1.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            ServiceReference1.GetRecIdFromKey inValue = new ServiceReference1.GetRecIdFromKey();
            inValue.Key = Key;
            return ((ServiceReference1.CashReceiptJournal_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Create_Result> CreateAsync(ServiceReference1.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CreateMultiple_Result> CreateMultipleAsync(ServiceReference1.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Update_Result> UpdateAsync(ServiceReference1.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.UpdateMultiple_Result> UpdateMultipleAsync(ServiceReference1.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.Delete_Result> ServiceReference1.CashReceiptJournal_Port.DeleteAsync(ServiceReference1.Delete request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Delete_Result> DeleteAsync(string CurrentJnlBatchName, string Key)
        {
            ServiceReference1.Delete inValue = new ServiceReference1.Delete();
            inValue.CurrentJnlBatchName = CurrentJnlBatchName;
            inValue.Key = Key;
            return ((ServiceReference1.CashReceiptJournal_Port)(this)).DeleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CashReceiptJournal_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CashReceiptJournal_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://20.87.10.102:30147/SBUBNZ/WS/TEST MY VOLTAGE/Page/CashReceiptJournal?tenant=1f998" +
                        "066-df97-4de7-875d-0179278815b1");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CashReceiptJournal_PortClient.GetBindingForEndpoint(EndpointConfiguration.CashReceiptJournal_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CashReceiptJournal_PortClient.GetEndpointAddress(EndpointConfiguration.CashReceiptJournal_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            CashReceiptJournal_Port,
        }
    }
}
