// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Notifications.Data;
using System;

namespace Notifications.Migrations
{
    [DbContext(typeof(MyVoltageNotificationDbContext))]
    partial class MyVoltageNotificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MyVoltage.Data.AccountType", b =>
                {
                    b.Property<int>("AccountTypeID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("AccountTypeID");

                    b.ToTable("AccountTypes");
                });

            modelBuilder.Entity("MyVoltage.Data.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<bool>("Registrable");

                    b.Property<string>("ServiceKey");

                    b.HasKey("CompanyID");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("MyVoltage.Data.CompanySkins", b =>
                {
                    b.Property<int>("CompanySkinsID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CompanyID");

                    b.Property<string>("Logo");

                    b.Property<string>("LogoWhite");

                    b.Property<string>("PrimaryColor");

                    b.Property<string>("SecondaryColor");

                    b.Property<string>("Url");

                    b.HasKey("CompanySkinsID");

                    b.ToTable("CompanySkins");
                });

            modelBuilder.Entity("MyVoltage.Data.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountTypeID");

                    b.Property<string>("AltPhoneNumber");

                    b.Property<int>("CompanyID");

                    b.Property<string>("ComplexName");

                    b.Property<string>("CustomerNumber");

                    b.Property<int?>("DisconnectionLowBalanceNotification1");

                    b.Property<int?>("DisconnectionLowBalanceNotification2");

                    b.Property<string>("DisconnectionNotices");

                    b.Property<string>("EmailCode");

                    b.Property<string>("FullName");

                    b.Property<bool>("HighUsageNotifications");

                    b.Property<string>("IDNumberOrCompanyReg");

                    b.Property<bool>("LeakNotifications");

                    b.Property<string>("MeterNumber");

                    b.Property<bool>("NewsLetters");

                    b.Property<string>("NotificationEmail");

                    b.Property<string>("NotificationPhoneNumber");

                    b.Property<string>("OTPCode");

                    b.Property<DateTime>("OccupancyDate");

                    b.Property<string>("PhoneNumber");

                    b.Property<int?>("PostalCode");

                    b.Property<string>("Province");

                    b.Property<string>("StreetAddress");

                    b.Property<string>("Suburb");

                    b.Property<string>("TownOrCity");

                    b.Property<string>("UnitNumber");

                    b.Property<string>("UserID")
                        .HasColumnType("VARCHAR(500)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MyVoltage.Data.CustomerMeter", b =>
                {
                    b.Property<int>("CustomerMeterID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CustomerID");

                    b.Property<int>("MeterNumber");

                    b.HasKey("CustomerMeterID");

                    b.ToTable("CustomerMeters");
                });

            modelBuilder.Entity("MyVoltage.Data.CustomerMeterType", b =>
                {
                    b.Property<int>("CustomerMeterTypeID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CustomerMeterID");

                    b.Property<int>("MeterTypeID");

                    b.Property<int>("Selected");

                    b.HasKey("CustomerMeterTypeID");

                    b.ToTable("CustomerMeterTypes");
                });

            modelBuilder.Entity("MyVoltage.Data.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<string>("CardHolderIpAddr");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Extra1");

                    b.Property<string>("Extra2");

                    b.Property<string>("Extra3");

                    b.Property<int?>("PaymentMethodID");

                    b.Property<int?>("PaymentStatusID");

                    b.Property<string>("Reason");

                    b.Property<string>("Reference");

                    b.Property<string>("RequestTrace");

                    b.Property<string>("UserID")
                        .HasColumnType("VARCHAR(500)");

                    b.HasKey("PaymentID");

                    b.HasIndex("PaymentMethodID");

                    b.HasIndex("PaymentStatusID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MyVoltage.Data.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("PaymentMethodID");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("MyVoltage.Data.PaymentRawData", b =>
                {
                    b.Property<int>("PaymentRawDataID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Error");

                    b.Property<DateTime>("PostingDate");

                    b.Property<string>("RawData");

                    b.HasKey("PaymentRawDataID");

                    b.ToTable("PaymentRawData");
                });

            modelBuilder.Entity("MyVoltage.Data.PaymentStatus", b =>
                {
                    b.Property<int>("PaymentStatusID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("PaymentStatusID");

                    b.ToTable("PaymentStatuses");
                });

            modelBuilder.Entity("MyVoltage.Data.UniPin", b =>
                {
                    b.Property<int>("UniPinID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<decimal>("Balance");

                    b.Property<decimal>("ConvenienceFee");

                    b.Property<DateTime>("CreateDate");

                    b.Property<decimal>("LoadedAmount");

                    b.Property<string>("Message");

                    b.Property<string>("MeterNumber");

                    b.Property<decimal>("PaidAmount");

                    b.Property<string>("ReferenceID");

                    b.Property<DateTime>("RequestDate");

                    b.Property<int>("ResponseStatus");

                    b.Property<string>("UserAddress");

                    b.Property<string>("UserID");

                    b.Property<string>("UserName");

                    b.HasKey("UniPinID");

                    b.ToTable("UniPins");
                });

            modelBuilder.Entity("MyVoltage.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("IsConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Notifications.Data.NotificationCustomerMeter", b =>
                {
                    b.Property<int>("NotificationCustomerMeterID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CustomerID");

                    b.Property<bool>("DisconnectNotification");

                    b.Property<bool>("LowBalanceNotification1");

                    b.Property<bool>("LowBalanceNotification2");

                    b.Property<string>("MeterSerial");

                    b.HasKey("NotificationCustomerMeterID");

                    b.ToTable("NotificationCustomerMeters");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MyVoltage.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MyVoltage.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyVoltage.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MyVoltage.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MyVoltage.Data.Payment", b =>
                {
                    b.HasOne("MyVoltage.Data.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodID");

                    b.HasOne("MyVoltage.Data.PaymentStatus", "PaymentStatus")
                        .WithMany()
                        .HasForeignKey("PaymentStatusID");
                });
#pragma warning restore 612, 618
        }
    }
}
